package com.voxleaf.reader.tts

import android.content.Context
import android.content.Intent
import android.media.AudioAttributes
import android.media.AudioFocusRequest
import android.media.AudioManager
import android.media.MediaPlayer
import android.os.PowerManager
import com.voxleaf.reader.data.local.datastore.AppSettingsManager
import com.voxleaf.reader.playback.PlaybackService
import dagger.Lazy
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

/**
 * What book/chapter the currently buffered [TtsManager] session belongs to. Lets UI outside the
 * Reader screen — a persistent mini player, notifications — show and navigate to what's playing
 * without owning any sentence-splitting logic of its own.
 */
data class NowPlaying(
    val bookId: String,
    val bookTitle: String,
    val chapterIndex: Int,
    val chapterTitle: String,
    val coverImagePath: String? = null
)

data class TtsChapter(val nowPlaying: NowPlaying, val text: String)

internal fun nextPlayableChapter(
    chapters: List<TtsChapter>,
    afterIndex: Int
): Pair<Int, List<String>>? {
    for (index in afterIndex + 1..chapters.lastIndex) {
        val sentences = TtsTextParser.sentences(chapters[index].text)
        if (sentences.isNotEmpty()) return index to sentences
    }
    return null
}

data class TtsState(
    val isInitialized: Boolean = true,
    val isSpeaking: Boolean = false,
    val isPaused: Boolean = false,
    val isPreparing: Boolean = false,
    val errorMessage: String? = null,
    val currentSentenceIndex: Int = 0,
    val totalSentences: Int = 0,
    val speechRate: Float = 1.0f,
    val engineId: EngineId = EngineId.OFFLINE,
    val isLoadingVoices: Boolean = false,
    val selectedVoicePath: String = SherpaTtsEngine.DEFAULT_VOICE,
    val availableVoices: List<EngineVoice> = SherpaTtsEngine.NARRATOR_PRESETS.map {
        EngineVoice(id = SherpaTtsEngine.voiceId(it.speakerId), displayName = it.displayName, locale = "en-US")
    },
    val sleepTimerMinutes: Int? = null,
    /**
     * Estimated clock for the current chapter, in milliseconds.
     *
     * Streamed sentences are synthesized one at a time, so there is no single decoded file whose
     * duration could be read; the position is estimated from word counts at a narration pace. Good
     * enough to drive a lock-screen scrubber, and deliberately not presented as exact.
     */
    val estimatedPositionMs: Long = 0L,
    val estimatedDurationMs: Long = 0L,
    val nowPlaying: NowPlaying? = null,
    val playbackCompletionId: Long = 0
)

/** Plays audio generated by whichever [TtsEngine] is currently selected — offline by default. */
@Singleton
class TtsManager @Inject constructor(
    @ApplicationContext private val context: Context,
    @OfflineEngine private val offlineEngine: Lazy<TtsEngine>,
    @OnlineEngine private val edgeEngine: Lazy<TtsEngine>,
    private val appSettingsManager: AppSettingsManager
) {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)
    private val _state = MutableStateFlow(TtsState())
    val state: StateFlow<TtsState> = _state.asStateFlow()

    private var currentSentences: List<String> = emptyList()
    private var chapterQueue: List<TtsChapter> = emptyList()
    private var chapterQueueIndex = -1
    private var player: MediaPlayer? = null
    private var playerPrepared = false
    private var currentAudioFile: java.io.File? = null
    private var playbackGeneration = 0
    private val bufferedAudio = mutableMapOf<Int, java.io.File>()
    private var bufferingJob: Job? = null
    private var nextSentenceToBuffer = 0
    private var nextSentenceToPlay = 0
    private var waitingForInitialBuffer = false
    private var sleepTimerJob: Job? = null
    /** Guards against an earlier engine switch landing after a later one. */
    private var engineSwitchToken = 0

    private val audioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager
    private val audioAttributes = AudioAttributes.Builder()
        .setUsage(AudioAttributes.USAGE_MEDIA)
        .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
        .build()
    private var pausedByFocusLoss = false
    private val focusRequest = AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN)
        .setAudioAttributes(audioAttributes)
        .setOnAudioFocusChangeListener { change ->
            when (change) {
                // Permanent loss still means "someone else is using audio now", not "end the
                // book" — stop() used to wipe chapterQueue/nowPlaying/position, so a phone call
                // permanently threw away the listener's place mid-book.
                AudioManager.AUDIOFOCUS_LOSS,
                AudioManager.AUDIOFOCUS_LOSS_TRANSIENT,
                AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK -> {
                    if (_state.value.isSpeaking) {
                        pausedByFocusLoss = true
                        pause()
                    }
                }
                AudioManager.AUDIOFOCUS_GAIN -> {
                    if (pausedByFocusLoss) {
                        pausedByFocusLoss = false
                        resume()
                    }
                }
            }
        }
        .build()

    fun speakSentences(sentences: List<String>, startIndex: Int = 0) {
        chapterQueue = emptyList()
        chapterQueueIndex = -1
        startSentenceSession(sentences, startIndex, _state.value.nowPlaying)
    }

    fun speakChapters(chapters: List<TtsChapter>, startChapterIndex: Int, startSentenceIndex: Int = 0) {
        chapterQueue = chapters
        val requested = chapters.indexOfFirst { it.nowPlaying.chapterIndex == startChapterIndex }
            .takeIf { it >= 0 } ?: 0
        val next = nextPlayableChapter(chapters, requested - 1) ?: return
        chapterQueueIndex = next.first
        startSentenceSession(next.second, startSentenceIndex, chapters[next.first].nowPlaying)
    }

    /** Words before [sentenceIndex], and in the whole chapter, converted to milliseconds. */
    private fun estimateClock(sentenceIndex: Int): Pair<Long, Long> {
        if (currentSentences.isEmpty()) return 0L to 0L
        val rate = _state.value.speechRate.coerceAtLeast(0.1f)
        val wordsPerMs = (WORDS_PER_MINUTE * rate) / 60_000f
        fun words(range: List<String>) = range.sumOf { sentence ->
            sentence.split(WHITESPACE).count { it.isNotBlank() }
        }
        val spoken = words(currentSentences.subList(0, sentenceIndex.coerceIn(0, currentSentences.size)))
        val total = words(currentSentences)
        return (spoken / wordsPerMs).toLong() to (total / wordsPerMs).toLong()
    }

    private fun publishClock(sentenceIndex: Int) {
        val (position, duration) = estimateClock(sentenceIndex)
        _state.update { it.copy(estimatedPositionMs = position, estimatedDurationMs = duration) }
    }

    /** Maps a lock-screen / Android Auto scrub back onto the sentence that covers that moment. */
    fun seekToMillis(positionMs: Long) {
        if (currentSentences.isEmpty()) return
        val rate = _state.value.speechRate.coerceAtLeast(0.1f)
        val wordsPerMs = (WORDS_PER_MINUTE * rate) / 60_000f
        var elapsed = 0f
        val target = positionMs.coerceAtLeast(0L)
        currentSentences.forEachIndexed { index, sentence ->
            elapsed += sentence.split(WHITESPACE).count { it.isNotBlank() } / wordsPerMs
            if (elapsed >= target) {
                seekToSentence(index)
                return
            }
        }
        seekToSentence(currentSentences.lastIndex)
    }

    fun seekToSentence(sentenceIndex: Int) {
        if (currentSentences.isEmpty()) return
        startSentenceSession(currentSentences, sentenceIndex, _state.value.nowPlaying)
    }

    private fun startSentenceSession(sentences: List<String>, startIndex: Int, nowPlaying: NowPlaying?) {
        if (audioManager.requestAudioFocus(focusRequest) != AudioManager.AUDIOFOCUS_REQUEST_GRANTED) return
        context.startForegroundService(Intent(context, PlaybackService::class.java))
        stopPlayer()
        clearBufferedAudio()
        currentSentences = sentences
        val start = startIndex.coerceIn(0, sentences.lastIndex.coerceAtLeast(0))
        val generation = ++playbackGeneration
        nextSentenceToBuffer = start
        nextSentenceToPlay = start
        waitingForInitialBuffer = sentences.isNotEmpty()
        _state.update {
            it.copy(
                isSpeaking = false,
                isPaused = false,
                isPreparing = sentences.isNotEmpty(),
                errorMessage = null,
                currentSentenceIndex = start,
                totalSentences = sentences.size,
                nowPlaying = nowPlaying
            )
        }
        publishClock(start)
        if (sentences.isNotEmpty()) startBuffering(generation)
    }

    fun pause() {
        if (_state.value.isPreparing) {
            _state.update { it.copy(isSpeaking = false, isPaused = true, isPreparing = false) }
            return
        }
        val activePlayer = player ?: return
        if (activePlayer.isPlaying) {
            activePlayer.pause()
            _state.update { it.copy(isSpeaking = false, isPaused = true) }
        }
    }

    fun resume() {
        val activePlayer = player
        if (!_state.value.isPaused) return
        if (audioManager.requestAudioFocus(focusRequest) != AudioManager.AUDIOFOCUS_REQUEST_GRANTED) return
        when {
            activePlayer != null && playerPrepared -> {
                activePlayer.start()
                _state.update { it.copy(isSpeaking = true, isPaused = false, isPreparing = false) }
            }
            activePlayer != null -> _state.update { it.copy(isPaused = false, isPreparing = true) }
            currentSentences.isNotEmpty() -> {
                _state.update { it.copy(isPaused = false, isPreparing = true) }
                startBufferedPlaybackIfReady(playbackGeneration)
            }
        }
    }

    /** Uses the retained chapter snapshot to replay after completion or a recoverable TTS error. */
    fun togglePlayback() {
        when {
            _state.value.isSpeaking || _state.value.isPreparing -> pause()
            _state.value.isPaused -> resume()
            currentSentences.isNotEmpty() -> seekToSentence(_state.value.currentSentenceIndex)
        }
    }

    fun stop() {
        ++playbackGeneration
        stopPlayer()
        clearBufferedAudio()
        chapterQueue = emptyList()
        chapterQueueIndex = -1
        sleepTimerJob?.cancel()
        sleepTimerJob = null
        audioManager.abandonAudioFocusRequest(focusRequest)
        context.stopService(Intent(context, PlaybackService::class.java))
        _state.update {
            it.copy(
                isSpeaking = false,
                isPaused = false,
                isPreparing = false,
                currentSentenceIndex = 0,
                sleepTimerMinutes = null,
                nowPlaying = null
            )
        }
    }

    /**
     * Set once, right before [speakSentences] starts a fresh session — deliberately not touched by
     * [skip] or the voice/rate rebuffer, both of which continue the same session, and cleared by
     * [stop] since that ends it. This is what lets a mini player outside the Reader screen show and
     * link back to what's playing without holding any chapter text itself.
     */
    fun setNowPlaying(info: NowPlaying?) {
        _state.update { it.copy(nowPlaying = info) }
    }

    fun skip(delta: Int) {
        if (currentSentences.isEmpty()) return
        val newIndex = (_state.value.currentSentenceIndex + delta).coerceIn(0, currentSentences.lastIndex)
        seekToSentence(newIndex)
    }

    fun setSleepTimer(minutes: Int?) {
        sleepTimerJob?.cancel()
        _state.update { it.copy(sleepTimerMinutes = minutes) }
        sleepTimerJob = minutes?.let { m ->
            scope.launch {
                delay(m * 60_000L)
                stop()
            }
        }
    }

    fun setSpeechRate(rate: Float) {
        val coerced = rate.coerceIn(0.5f, 2f)
        if (kotlin.math.abs(coerced - _state.value.speechRate) < 0.02f) return
        _state.update { it.copy(speechRate = coerced) }
        // Persisted here (not by callers' own viewModelScope) so the write survives the caller
        // navigating away right after — a screen's viewModelScope is cancelled on that navigation
        // and would silently drop an in-flight DataStore write.
        scope.launch { appSettingsManager.setTtsRate(coerced) }
        rebufferAheadOfPlayhead()
    }


    fun setVoice(voicePath: String) {
        if (voicePath == _state.value.selectedVoicePath) return
        _state.update { it.copy(selectedVoicePath = voicePath) }
        scope.launch { appSettingsManager.setTtsVoice(voicePath) }
        rebufferAheadOfPlayhead()
    }

    /**
     * Switches the active [TtsEngine], picking a sensible default voice. Voice ids are
     * engine-specific, so the previous selection can't carry over.
     */
    fun setEngine(id: EngineId) {
        if (id == _state.value.engineId) return
        scope.launch { appSettingsManager.setTtsEngine(id.storageKey) }
        switchEngine(id, preferredVoiceId = null)
    }

    /**
     * Applies a persisted (engine, voice) pair together, e.g. on app start. Using one call instead of
     * setting engine and voice independently avoids a real race: switching engines re-fetches that
     * engine's voice list asynchronously (a network call for Edge) and only then can a voice id be
     * validated against it — a separate, concurrent `setVoice` call has no way to know when that
     * fetch has landed.
     */
    fun setEngineAndVoice(id: EngineId, preferredVoiceId: String) {
        if (id == _state.value.engineId) {
            setVoice(preferredVoiceId)
        } else {
            switchEngine(id, preferredVoiceId)
        }
    }

    /**
     * The engine and the voice list it offers are changed in one update, never separately.
     *
     * Setting the engine up front and filling in its voices when they arrived left a window — and,
     * if the fetch failed, a permanent state — where the app reported one engine while holding the
     * other's voices. The reader then showed a bundled offline narrator labelled "Online", and
     * synthesis was asked for a voice the active engine does not have.
     */
    private fun switchEngine(id: EngineId, preferredVoiceId: String?) {
        val token = ++engineSwitchToken
        _state.update { it.copy(isLoadingVoices = true, errorMessage = null) }
        scope.launch {
            val voices = engineFor(id).listVoices()
            // A later switch has superseded this one; its result is what should stand.
            if (token != engineSwitchToken) return@launch
            if (voices.isEmpty()) {
                _state.update {
                    it.copy(
                        isLoadingVoices = false,
                        errorMessage = if (id == EngineId.EDGE) {
                            "Could not load Edge TTS voices. Check your connection and try again."
                        } else {
                            it.errorMessage
                        }
                    )
                }
                // Keep the stored preference in step with the engine that is actually active, or
                // every launch would retry the switch and land back in the same broken state.
                if (id != _state.value.engineId) {
                    appSettingsManager.setTtsEngine(_state.value.engineId.storageKey)
                }
                return@launch
            }
            val chosen = voices.firstOrNull { it.id == preferredVoiceId }
                ?: voices.firstOrNull { it.locale.startsWith("en-US") && it.displayName.contains("Aria", ignoreCase = true) }
                ?: voices.first()
            _state.update {
                it.copy(
                    engineId = id,
                    availableVoices = voices,
                    selectedVoicePath = chosen.id,
                    isLoadingVoices = false
                )
            }
            rebufferAheadOfPlayhead()
        }
    }

    private fun engineFor(id: EngineId): TtsEngine = if (id == EngineId.EDGE) edgeEngine.get() else offlineEngine.get()
    private fun activeEngine(): TtsEngine = engineFor(_state.value.engineId)

    /**
     * The sentence already loaded into the player keeps playing in the old voice/rate — swapping
     * audio out from under a MediaPlayer mid-playback would just glitch. Everything queued behind it
     * has not been heard yet, though, so it's cheap and correct to discard and re-synthesize: without
     * this, a listener who didn't like a voice heard up to [TARGET_BUFFERED_SENTENCES] more sentences
     * in it before the switch "took", which reads as the picker being broken.
     *
     * Deliberately does NOT bump [playbackGeneration]: that counter is what the active player's own
     * onPrepared/onCompletion/onError closures were captured with, and bumping it here would make
     * onCompletion's generation check fail for the sentence already playing — silently stopping
     * playback after it instead of continuing into the re-buffered queue.
     */
    private fun rebufferAheadOfPlayhead() {
        if (currentSentences.isEmpty()) return
        val outgoing = bufferingJob
        val generation = playbackGeneration
        scope.launch {
            // Wait for any in-flight synthesis to actually stop before touching the map: otherwise a
            // write from the old (stale voice/rate) call can land after the map is cleared and poison
            // the very index the new buffering pass is about to fill.
            outgoing?.cancelAndJoin()
            if (generation != playbackGeneration) return@launch
            bufferedAudio.values.forEach { it.delete() }
            bufferedAudio.clear()
            // The sentence currently loaded in `player` (playing or paused) is `nextSentenceToPlay`
            // itself — it only advances on completion — so buffering must resume one past it.
            nextSentenceToBuffer = if (player != null) nextSentenceToPlay + 1 else nextSentenceToPlay
            waitingForInitialBuffer = false
            startBuffering(generation)
        }
    }

    fun shutdown() = stop()

    private fun startBuffering(generation: Int) {
        bufferingJob?.cancel()
        bufferingJob = scope.launch {
            while (generation == playbackGeneration && nextSentenceToBuffer < currentSentences.size) {
                if (bufferedAudio.size >= TARGET_BUFFERED_SENTENCES) {
                    delay(BUFFER_CHECK_DELAY_MS)
                    continue
                }
                val index = nextSentenceToBuffer
                val engine = activeEngine()
                var audioFile = runCatching {
                    engine.synthesize(currentSentences[index], _state.value.selectedVoicePath, _state.value.speechRate)
                }.getOrNull()
                // A network drop mid-chapter used to just kill playback outright. The offline voice
                // is always bundled, so falling back to it for this one sentence keeps audio going
                // instead of stopping a listener because Wi-Fi hiccuped for a few seconds; playback
                // stays on the online voice otherwise, this doesn't switch the persisted engine.
                var usedFallback = false
                if (audioFile == null && engine.requiresNetwork) {
                    audioFile = runCatching {
                        offlineEngine.get().synthesize(currentSentences[index], SherpaTtsEngine.DEFAULT_VOICE, _state.value.speechRate)
                    }.getOrNull()
                    usedFallback = audioFile != null
                }
                if (generation != playbackGeneration) {
                    audioFile?.delete()
                    return@launch
                }
                if (audioFile == null) {
                    _state.update {
                        it.copy(
                            isSpeaking = false,
                            isPaused = false,
                            isPreparing = false,
                            errorMessage = if (engine.requiresNetwork) {
                                "Edge TTS could not generate audio. Check your connection and try again."
                            } else {
                                "The bundled offline voice could not generate audio. Please try again."
                            }
                        )
                    }
                    return@launch
                }
                if (usedFallback) {
                    _state.update { it.copy(errorMessage = "Connection lost — switched to the offline voice for this chapter.") }
                }
                bufferedAudio[index] = audioFile
                nextSentenceToBuffer += 1
                startBufferedPlaybackIfReady(generation)
            }
        }
    }

    private fun startBufferedPlaybackIfReady(generation: Int) {
        if (generation != playbackGeneration || player != null || _state.value.isPaused) return
        // Starting is gated on a couple of sentences, not on the full buffer: both engines synthesize
        // faster than speech is spoken, so the buffer keeps growing on its own once playback is under
        // way. Waiting for the whole target before the first word only ever added silence at the front.
        val initialTarget = minOf(START_PLAYBACK_AFTER_SENTENCES, currentSentences.size - nextSentenceToPlay)
        if (waitingForInitialBuffer && bufferedAudio.size < initialTarget) return
        val audioFile = bufferedAudio.remove(nextSentenceToPlay) ?: return
        waitingForInitialBuffer = false
        startPlayback(generation, nextSentenceToPlay, audioFile)
    }

    private fun startNextQueuedChapter(generation: Int): Boolean {
        if (generation != playbackGeneration || chapterQueue.isEmpty()) return false
        val next = nextPlayableChapter(chapterQueue, chapterQueueIndex) ?: return false
        chapterQueueIndex = next.first
        startSentenceSession(next.second, 0, chapterQueue[next.first].nowPlaying)
        return true
    }

    private fun startPlayback(generation: Int, index: Int, audioFile: java.io.File) {
        if (generation != playbackGeneration) {
            audioFile.delete()
            return
        }
        val nextPlayer = MediaPlayer()
        try {
            nextPlayer.setAudioAttributes(audioAttributes)
            nextPlayer.setWakeMode(context, PowerManager.PARTIAL_WAKE_LOCK)
            nextPlayer.setDataSource(audioFile.path)
            nextPlayer.setOnPreparedListener { preparedPlayer ->
                if (generation != playbackGeneration || player !== preparedPlayer) {
                    preparedPlayer.release()
                    audioFile.delete()
                    return@setOnPreparedListener
                }
                playerPrepared = true
                if (_state.value.isPaused) return@setOnPreparedListener
                preparedPlayer.start()
                _state.update { it.copy(isSpeaking = true, isPaused = false, isPreparing = false, currentSentenceIndex = index) }
                publishClock(index)
            }
            nextPlayer.setOnCompletionListener { completedPlayer ->
                completedPlayer.release()
                audioFile.delete()
                if (player === completedPlayer) {
                    player = null
                    playerPrepared = false
                    currentAudioFile = null
                }
                if (generation == playbackGeneration) {
                    nextSentenceToPlay = index + 1
                    if (nextSentenceToPlay >= currentSentences.size && startNextQueuedChapter(generation)) {
                        return@setOnCompletionListener
                    }
                    _state.update {
                        it.copy(
                            isSpeaking = false,
                            isPaused = false,
                            isPreparing = nextSentenceToPlay < currentSentences.size,
                            playbackCompletionId = if (nextSentenceToPlay >= currentSentences.size) {
                                it.playbackCompletionId + 1
                            } else {
                                it.playbackCompletionId
                            }
                        )
                    }
                    startBufferedPlaybackIfReady(generation)
                }
            }
            nextPlayer.setOnErrorListener { failedPlayer, _, _ ->
                failedPlayer.release()
                audioFile.delete()
                if (player === failedPlayer) {
                    player = null
                    playerPrepared = false
                    currentAudioFile = null
                }
                _state.update {
                    it.copy(isSpeaking = false, isPaused = false, isPreparing = false, errorMessage = "Vox Reader could not play that sentence.")
                }
                true
            }
            player = nextPlayer
            playerPrepared = false
            currentAudioFile = audioFile
            _state.update { it.copy(isSpeaking = false, isPaused = false, isPreparing = true, currentSentenceIndex = index) }
            nextPlayer.prepareAsync()
        } catch (_: Exception) {
            nextPlayer.release()
            audioFile.delete()
            if (player === nextPlayer) {
                player = null
                playerPrepared = false
                currentAudioFile = null
            }
            _state.update {
                it.copy(isSpeaking = false, isPaused = false, isPreparing = false, errorMessage = "Vox Reader could not prepare that sentence.")
            }
        }
    }

    private fun clearBufferedAudio() {
        bufferingJob?.cancel()
        bufferingJob = null
        bufferedAudio.values.forEach { it.delete() }
        bufferedAudio.clear()
        waitingForInitialBuffer = false
    }

    private fun stopPlayer() {
        player?.run {
            setOnCompletionListener(null)
            setOnPreparedListener(null)
            setOnErrorListener(null)
            runCatching { stop() }
            release()
        }
        player = null
        playerPrepared = false
        currentAudioFile?.delete()
        currentAudioFile = null
    }

    private companion object {
        /**
         * How far ahead of the voice the buffer runs. Deep on purpose: a sentence is only a few
         * seconds of audio, so a shallow buffer leaves playback one slow synthesis away from a gap —
         * a dropped network response on the online engine, or a thermally throttled core on the
         * offline one. Two dozen sentences is a couple of minutes of runway and costs a few MB of
         * short WAVs, which is a good trade against stuttering.
         */
        const val TARGET_BUFFERED_SENTENCES = 24

        /** Start playback on the very first synthesized sentence; remaining sentences synthesize concurrently. */
        const val START_PLAYBACK_AFTER_SENTENCES = 1
        const val BUFFER_CHECK_DELAY_MS = 50L

        /** Conversational narration pace, matching the Reader's own scrubber estimate. */
        const val WORDS_PER_MINUTE = 155f
        val WHITESPACE = Regex("\\s+")
    }
}
